"""create initial application schema

Revision ID: 5eead3cb186c
Revises:
Create Date: 2026-08-07 09:28:26.178176
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5eead3cb186c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notices")),
    )
    op.create_index(
        "ix_notices_active_pinned_published",
        "notices",
        ["is_active", "is_pinned", "published_at"],
        unique=False,
    )
    op.create_table(
        "place_tags",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_tags")),
        sa.UniqueConstraint("code", name=op.f("uq_place_tags_code")),
    )
    op.create_table(
        "route_calculation_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("origin_latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("origin_longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("destination_latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("destination_longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column(
            "transport",
            sa.Enum(
                "rental_car",
                "own_car",
                "taxi",
                "public_transport",
                "walk",
                "ferry",
                "airplane",
                name="transport_type",
            ),
            nullable=False,
        ),
        sa.Column("requested_departure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("distance_meters", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "destination_latitude BETWEEN -90 AND 90",
            name=op.f("ck_route_calculation_cache_destination_latitude_range"),
        ),
        sa.CheckConstraint(
            "destination_longitude BETWEEN -180 AND 180",
            name=op.f("ck_route_calculation_cache_destination_longitude_range"),
        ),
        sa.CheckConstraint(
            "distance_meters >= 0", name=op.f("ck_route_calculation_cache_distance_nonnegative")
        ),
        sa.CheckConstraint(
            "duration_minutes >= 0", name=op.f("ck_route_calculation_cache_duration_nonnegative")
        ),
        sa.CheckConstraint(
            "expires_at > calculated_at", name=op.f("ck_route_calculation_cache_expiry_order")
        ),
        sa.CheckConstraint(
            "origin_latitude BETWEEN -90 AND 90",
            name=op.f("ck_route_calculation_cache_origin_latitude_range"),
        ),
        sa.CheckConstraint(
            "origin_longitude BETWEEN -180 AND 180",
            name=op.f("ck_route_calculation_cache_origin_longitude_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_calculation_cache")),
    )
    op.create_index(
        "ix_route_calculation_cache_expires_at",
        "route_calculation_cache",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "auth_provider",
            sa.Enum("local", "kakao", "apple", "google", name="auth_provider"),
            server_default="local",
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.String(length=255), nullable=True),
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("profile_image_url", sa.Text(), nullable=True),
        sa.Column(
            "inquiry_answer_notification_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "marketing_notification_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "auth_provider",
            "provider_user_id",
            name=op.f("uq_users_auth_provider_provider_user_id"),
        ),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "weather_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("forecast_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "condition",
            sa.Enum(
                "sunny",
                "partly_cloudy",
                "cloudy",
                "rainy",
                "snowy",
                "windy",
                name="weather_condition",
            ),
            nullable=False,
        ),
        sa.Column("temperature", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("min_temperature", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("max_temperature", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("precipitation_probability", sa.SmallInteger(), nullable=True),
        sa.Column("humidity", sa.SmallInteger(), nullable=True),
        sa.Column("wind_speed", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "humidity IS NULL OR humidity BETWEEN 0 AND 100",
            name=op.f("ck_weather_snapshots_humidity_range"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name=op.f("ck_weather_snapshots_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_weather_snapshots_longitude_range"),
        ),
        sa.CheckConstraint(
            "precipitation_probability IS NULL OR precipitation_probability BETWEEN 0 AND 100",
            name=op.f("ck_weather_snapshots_precipitation_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_snapshots")),
        sa.UniqueConstraint(
            "region", "forecast_at", name=op.f("uq_weather_snapshots_region_forecast_at")
        ),
    )
    op.create_table(
        "inquiries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_urls", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR (answer IS NOT NULL AND answered_at IS NOT NULL)",
            name=op.f("ck_inquiries_completed_has_answer"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed')", name=op.f("ck_inquiries_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_inquiries_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inquiries")),
    )
    op.create_index(
        "ix_inquiries_user_status_created",
        "inquiries",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("icon_key", sa.String(length=50), nullable=True),
        sa.Column("action_path", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "is_read = false OR read_at IS NOT NULL",
            name=op.f("ck_notifications_read_has_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_notifications_user_read_created",
        "notifications",
        ["user_id", "is_read", "created_at"],
        unique=False,
    )
    op.create_table(
        "pets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "species",
            sa.Enum("dog", "cat", "rabbit", "bird", "other", name="pet_species"),
            nullable=False,
        ),
        sa.Column("breed", sa.String(length=100), nullable=True),
        sa.Column("size", sa.Enum("small", "medium", "large", name="pet_size"), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("health_notes", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg >= 0", name=op.f("ck_pets_weight_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_pets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pets")),
    )
    op.create_index("ix_pets_user_active", "pets", ["user_id", "deleted_at"], unique=False)
    op.create_index(
        "uq_pets_user_primary_active",
        "pets",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = true AND deleted_at IS NULL"),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("road_address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("primary_image_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "description_source",
            sa.Enum(
                "tour_api",
                "kcisa",
                "visitjeju",
                "kakao",
                "tmap",
                "weather_api",
                "internal",
                name="data_provider",
            ),
            nullable=True,
        ),
        sa.Column(
            "environment",
            sa.Enum("indoor", "outdoor", "mixed", name="place_environment"),
            nullable=True,
        ),
        sa.Column("amenities", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("average_stay_minutes", sa.Integer(), nullable=True),
        sa.Column("activity_level", sa.SmallInteger(), nullable=True),
        sa.Column("crowd_level", sa.SmallInteger(), nullable=True),
        sa.Column("weather_sensitivity", sa.SmallInteger(), nullable=True),
        sa.Column(
            "reservation_required", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_level IS NULL OR activity_level BETWEEN 1 AND 5",
            name=op.f("ck_places_activity_level_range"),
        ),
        sa.CheckConstraint(
            "crowd_level IS NULL OR crowd_level BETWEEN 1 AND 5",
            name=op.f("ck_places_crowd_level_range"),
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_places_latitude_range")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_places_longitude_range")
        ),
        sa.CheckConstraint(
            "weather_sensitivity IS NULL OR weather_sensitivity BETWEEN 1 AND 5",
            name=op.f("ck_places_weather_sensitivity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_places_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
    )
    op.create_index("ix_places_category", "places", ["category"], unique=False)
    op.create_index("ix_places_created_by_user_id", "places", ["created_by_user_id"], unique=False)
    op.create_index(
        "ix_places_latitude_longitude", "places", ["latitude", "longitude"], unique=False
    )
    op.create_index("ix_places_region", "places", ["region"], unique=False)
    op.create_table(
        "user_travel_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "default_pace", sa.Enum("relaxed", "normal", "packed", name="trip_pace"), nullable=True
        ),
        sa.Column(
            "default_transport",
            sa.Enum(
                "rental_car",
                "own_car",
                "taxi",
                "public_transport",
                "walk",
                "ferry",
                "airplane",
                name="transport_type",
            ),
            nullable=True,
        ),
        sa.Column("departure_location", sa.String(length=100), nullable=True),
        sa.Column("preferred_duration_days", sa.Integer(), nullable=True),
        sa.Column("companion_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("preferred_tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "companion_count >= 1", name=op.f("ck_user_travel_preferences_companion_count_positive")
        ),
        sa.CheckConstraint(
            "preferred_duration_days IS NULL OR preferred_duration_days >= 1",
            name=op.f("ck_user_travel_preferences_duration_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_travel_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_travel_preferences")),
    )
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_favorites_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "place_id", name=op.f("pk_favorites")),
    )
    op.create_table(
        "place_business_hours",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("break_start_at", sa.Time(), nullable=True),
        sa.Column("break_end_at", sa.Time(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(break_start_at IS NULL) = (break_end_at IS NULL)",
            name=op.f("ck_place_business_hours_break_pair_complete"),
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN 0 AND 6", name=op.f("ck_place_business_hours_day_of_week_range")
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_business_hours_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_business_hours")),
        sa.UniqueConstraint(
            "place_id", "day_of_week", name=op.f("uq_place_business_hours_place_id_day_of_week")
        ),
    )
    op.create_table(
        "place_external_refs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "tour_api",
                "kcisa",
                "visitjeju",
                "kakao",
                "tmap",
                "weather_api",
                "internal",
                name="data_provider",
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_external_refs_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_external_refs")),
        sa.UniqueConstraint(
            "provider", "external_id", name=op.f("uq_place_external_refs_provider_external_id")
        ),
    )
    op.create_index(
        "ix_place_external_refs_place_provider",
        "place_external_refs",
        ["place_id", "provider"],
        unique=False,
    )
    op.create_table(
        "place_pet_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column(
            "policy_type",
            sa.Enum(
                "indoor_allowed",
                "outdoor_only",
                "partial_allowed",
                "not_allowed",
                "unknown",
                name="pet_policy_type",
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("allowed_species", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("allowed_sizes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("max_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("carrier_required", sa.Boolean(), nullable=True),
        sa.Column("leash_required", sa.Boolean(), nullable=True),
        sa.Column("vaccination_required", sa.Boolean(), nullable=True),
        sa.Column("extra_fee_amount", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "tour_api",
                "kcisa",
                "visitjeju",
                "kakao",
                "tmap",
                "weather_api",
                "internal",
                name="data_provider",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reliability_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.CheckConstraint(
            "extra_fee_amount IS NULL OR extra_fee_amount >= 0",
            name=op.f("ck_place_pet_policies_extra_fee_nonnegative"),
        ),
        sa.CheckConstraint(
            "max_weight_kg IS NULL OR max_weight_kg >= 0",
            name=op.f("ck_place_pet_policies_max_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "reliability_score IS NULL OR reliability_score BETWEEN 0 AND 100",
            name=op.f("ck_place_pet_policies_reliability_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_pet_policies_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_pet_policies")),
    )
    op.create_index(
        "ix_place_pet_policies_place_id", "place_pet_policies", ["place_id"], unique=False
    )
    op.create_table(
        "place_tag_links",
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "tour_api",
                "kcisa",
                "visitjeju",
                "kakao",
                "tmap",
                "weather_api",
                "internal",
                name="data_provider",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_place_tag_links_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_tag_links_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["place_tags.id"],
            name=op.f("fk_place_tag_links_tag_id_place_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("place_id", "tag_id", name=op.f("pk_place_tag_links")),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column("pet_id", sa.UUID(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("pet_policy_accurate", sa.Boolean(), nullable=True),
        sa.Column("visited_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["pet_id"], ["pets.id"], name=op.f("fk_reviews_pet_id_pets"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["places.id"], name=op.f("fk_reviews_place_id_places"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reviews_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index("ix_reviews_place_created", "reviews", ["place_id", "created_at"], unique=False)
    op.create_index("ix_reviews_user_created", "reviews", ["user_id", "created_at"], unique=False)
    op.create_table(
        "route_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("departure_location", sa.String(length=100), nullable=True),
        sa.Column("departure_place_id", sa.UUID(), nullable=True),
        sa.Column("pace", sa.Enum("relaxed", "normal", "packed", name="trip_pace"), nullable=False),
        sa.Column(
            "transport",
            sa.Enum(
                "rental_car",
                "own_car",
                "taxi",
                "public_transport",
                "walk",
                "ferry",
                "airplane",
                name="transport_type",
            ),
            nullable=False,
        ),
        sa.Column("companion_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("preferred_tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("request_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "companion_count >= 1", name=op.f("ck_route_requests_companion_count_positive")
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_route_requests_date_order")),
        sa.ForeignKeyConstraint(
            ["departure_place_id"],
            ["places.id"],
            name=op.f("fk_route_requests_departure_place_id_places"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_route_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_requests")),
    )
    op.create_index(
        "ix_route_requests_user_created", "route_requests", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "review_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_review_images_sort_order_nonnegative")),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_review_images_review_id_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_images")),
        sa.UniqueConstraint(
            "review_id", "sort_order", name=op.f("uq_review_images_review_id_sort_order")
        ),
    )
    op.create_table(
        "route_request_pets",
        sa.Column("route_request_id", sa.UUID(), nullable=False),
        sa.Column("pet_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
            name=op.f("fk_route_request_pets_pet_id_pets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["route_request_id"],
            ["route_requests.id"],
            name=op.f("fk_route_request_pets_route_request_id_route_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("route_request_id", "pet_id", name=op.f("pk_route_request_pets")),
    )
    op.create_table(
        "route_request_stays",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_request_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "check_out_at IS NULL OR check_in_at IS NULL OR check_out_at > check_in_at",
            name=op.f("ck_route_request_stays_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_route_request_stays_place_id_places"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["route_request_id"],
            ["route_requests.id"],
            name=op.f("fk_route_request_stays_route_request_id_route_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_request_stays")),
    )
    op.create_index(
        "ix_route_request_stays_request", "route_request_stays", ["route_request_id"], unique=False
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_request_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "generated",
                "saved",
                "ongoing",
                "completed",
                "failed",
                name="route_status",
            ),
            server_default="generating",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pace", sa.Enum("relaxed", "normal", "packed", name="trip_pace"), nullable=False),
        sa.Column(
            "transport",
            sa.Enum(
                "rental_car",
                "own_car",
                "taxi",
                "public_transport",
                "walk",
                "ferry",
                "airplane",
                name="transport_type",
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("total_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("pet_safety_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column("style_keywords", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("share_token", sa.String(length=100), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_routes_date_order")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_routes_version_positive")),
        sa.ForeignKeyConstraint(
            ["route_request_id"],
            ["route_requests.id"],
            name=op.f("fk_routes_route_request_id_route_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_routes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
        sa.UniqueConstraint(
            "route_request_id", "version", name=op.f("uq_routes_route_request_id_version")
        ),
        sa.UniqueConstraint("share_token", name=op.f("uq_routes_share_token")),
    )
    op.create_index("ix_routes_user_status", "routes", ["user_id", "status"], unique=False)
    op.create_table(
        "chat_conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_chat_conversations_route_id_routes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_conversations")),
    )
    op.create_index(
        "ix_chat_conversations_user_updated",
        "chat_conversations",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "route_checklist_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("is_checked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_recommended", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_route_checklist_items_sort_order_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_route_checklist_items_route_id_routes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_checklist_items")),
    )
    op.create_index(
        "ix_route_checklist_items_route_category",
        "route_checklist_items",
        ["route_id", "category"],
        unique=False,
    )
    op.create_table(
        "route_days",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("route_date", sa.Date(), nullable=False),
        sa.Column("weather_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.CheckConstraint("day_number >= 1", name=op.f("ck_route_days_day_number_positive")),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_route_days_route_id_routes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["weather_snapshot_id"],
            ["weather_snapshots.id"],
            name=op.f("fk_route_days_weather_snapshot_id_weather_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_days")),
        sa.UniqueConstraint(
            "route_id", "day_number", name=op.f("uq_route_days_route_id_day_number")
        ),
    )
    op.create_table(
        "travel_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=True),
        sa.Column("place_id", sa.UUID(), nullable=True),
        sa.Column("place_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("recorded_date", sa.Date(), nullable=False),
        sa.Column("visited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_image_url", sa.Text(), nullable=False),
        sa.Column("generated_image_url", sa.Text(), nullable=True),
        sa.Column("writing_style", sa.String(length=30), nullable=False),
        sa.Column("mood", sa.String(length=30), nullable=True),
        sa.Column("generation_status", sa.String(length=20), server_default="idle", nullable=False),
        sa.Column("personal_message", sa.Text(), nullable=True),
        sa.Column(
            "is_representative", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "generation_status IN ('idle', 'uploading', 'generating', 'completed', 'failed')",
            name=op.f("ck_travel_logs_generation_status_valid"),
        ),
        sa.CheckConstraint(
            "mood IS NULL OR mood IN ('happy', 'excited', 'relaxed', 'bittersweet')",
            name=op.f("ck_travel_logs_mood_valid"),
        ),
        sa.CheckConstraint(
            "writing_style IN ('dog_diary', 'jeju_dialect')",
            name=op.f("ck_travel_logs_writing_style_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_travel_logs_place_id_places"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_travel_logs_route_id_routes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_travel_logs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_travel_logs")),
    )
    op.create_index(
        "ix_travel_logs_place_recorded", "travel_logs", ["place_id", "recorded_date"], unique=False
    )
    op.create_index(
        "ix_travel_logs_route_recorded", "travel_logs", ["route_id", "recorded_date"], unique=False
    )
    op.create_index(
        "ix_travel_logs_user_recorded", "travel_logs", ["user_id", "recorded_date"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", "system", name="message_role"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("referenced_place_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["chat_conversations.id"],
            name=op.f("fk_chat_messages_conversation_id_chat_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        "ix_chat_messages_conversation_created",
        "chat_messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "route_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_day_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=True),
        sa.Column("custom_place_name", sa.String(length=200), nullable=True),
        sa.Column(
            "item_type",
            sa.Enum(
                "attraction",
                "restaurant",
                "cafe",
                "accommodation",
                "custom",
                name="schedule_item_type",
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stay_minutes", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("recommendation_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("recommendation_reason", sa.Text(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_route_items_date_order"),
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_route_items_sort_order_nonnegative")),
        sa.CheckConstraint(
            "stay_minutes IS NULL OR stay_minutes >= 0",
            name=op.f("ck_route_items_stay_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_route_items_place_id_places"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["route_day_id"],
            ["route_days.id"],
            name=op.f("fk_route_items_route_day_id_route_days"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_items")),
        sa.UniqueConstraint(
            "route_day_id", "sort_order", name=op.f("uq_route_items_route_day_id_sort_order")
        ),
    )
    op.create_table(
        "route_memos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("route_day_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["route_day_id"],
            ["route_days.id"],
            name=op.f("fk_route_memos_route_day_id_route_days"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_route_memos_route_id_routes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_memos")),
    )
    op.create_index(
        "ix_route_memos_route_day", "route_memos", ["route_id", "route_day_id"], unique=False
    )
    op.create_table(
        "travel_log_pets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("travel_log_id", sa.UUID(), nullable=False),
        sa.Column("pet_id", sa.UUID(), nullable=True),
        sa.Column("pet_name_snapshot", sa.String(length=50), nullable=False),
        sa.Column("pet_profile_image_snapshot", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
            name=op.f("fk_travel_log_pets_pet_id_pets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["travel_log_id"],
            ["travel_logs.id"],
            name=op.f("fk_travel_log_pets_travel_log_id_travel_logs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_travel_log_pets")),
        sa.UniqueConstraint(
            "travel_log_id", "pet_id", name=op.f("uq_travel_log_pets_travel_log_id_pet_id")
        ),
    )
    op.create_table(
        "route_moves",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_item_id", sa.UUID(), nullable=False),
        sa.Column("to_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "transport",
            sa.Enum(
                "rental_car",
                "own_car",
                "taxi",
                "public_transport",
                "walk",
                "ferry",
                "airplane",
                name="transport_type",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_item_id <> to_item_id", name=op.f("ck_route_moves_different_items")
        ),
        sa.ForeignKeyConstraint(
            ["from_item_id"],
            ["route_items.id"],
            name=op.f("fk_route_moves_from_item_id_route_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_item_id"],
            ["route_items.id"],
            name=op.f("fk_route_moves_to_item_id_route_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_moves")),
        sa.UniqueConstraint(
            "from_item_id", "to_item_id", name=op.f("uq_route_moves_from_item_id_to_item_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_moves")
    op.drop_table("travel_log_pets")
    op.drop_index("ix_route_memos_route_day", table_name="route_memos")
    op.drop_table("route_memos")
    op.drop_table("route_items")
    op.drop_index("ix_chat_messages_conversation_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_travel_logs_user_recorded", table_name="travel_logs")
    op.drop_index("ix_travel_logs_route_recorded", table_name="travel_logs")
    op.drop_index("ix_travel_logs_place_recorded", table_name="travel_logs")
    op.drop_table("travel_logs")
    op.drop_table("route_days")
    op.drop_index("ix_route_checklist_items_route_category", table_name="route_checklist_items")
    op.drop_table("route_checklist_items")
    op.drop_index("ix_chat_conversations_user_updated", table_name="chat_conversations")
    op.drop_table("chat_conversations")
    op.drop_index("ix_routes_user_status", table_name="routes")
    op.drop_table("routes")
    op.drop_index("ix_route_request_stays_request", table_name="route_request_stays")
    op.drop_table("route_request_stays")
    op.drop_table("route_request_pets")
    op.drop_table("review_images")
    op.drop_index("ix_route_requests_user_created", table_name="route_requests")
    op.drop_table("route_requests")
    op.drop_index("ix_reviews_user_created", table_name="reviews")
    op.drop_index("ix_reviews_place_created", table_name="reviews")
    op.drop_table("reviews")
    op.drop_table("place_tag_links")
    op.drop_index("ix_place_pet_policies_place_id", table_name="place_pet_policies")
    op.drop_table("place_pet_policies")
    op.drop_index("ix_place_external_refs_place_provider", table_name="place_external_refs")
    op.drop_table("place_external_refs")
    op.drop_table("place_business_hours")
    op.drop_table("favorites")
    op.drop_table("user_travel_preferences")
    op.drop_index("ix_places_region", table_name="places")
    op.drop_index("ix_places_latitude_longitude", table_name="places")
    op.drop_index("ix_places_created_by_user_id", table_name="places")
    op.drop_index("ix_places_category", table_name="places")
    op.drop_table("places")
    op.drop_index(
        "uq_pets_user_primary_active",
        table_name="pets",
        postgresql_where=sa.text("is_primary = true AND deleted_at IS NULL"),
    )
    op.drop_index("ix_pets_user_active", table_name="pets")
    op.drop_table("pets")
    op.drop_index("ix_notifications_user_read_created", table_name="notifications")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_inquiries_user_status_created", table_name="inquiries")
    op.drop_table("inquiries")
    op.drop_table("weather_snapshots")
    op.drop_table("users")
    op.drop_index("ix_route_calculation_cache_expires_at", table_name="route_calculation_cache")
    op.drop_table("route_calculation_cache")
    op.drop_table("place_tags")
    op.drop_index("ix_notices_active_pinned_published", table_name="notices")
    op.drop_table("notices")
    op.execute("DROP TYPE IF EXISTS message_role")
    op.execute("DROP TYPE IF EXISTS schedule_item_type")
    op.execute("DROP TYPE IF EXISTS route_status")
    op.execute("DROP TYPE IF EXISTS pet_policy_type")
    op.execute("DROP TYPE IF EXISTS place_environment")
    op.execute("DROP TYPE IF EXISTS data_provider")
    op.execute("DROP TYPE IF EXISTS weather_condition")
    op.execute("DROP TYPE IF EXISTS transport_type")
    op.execute("DROP TYPE IF EXISTS trip_pace")
    op.execute("DROP TYPE IF EXISTS pet_size")
    op.execute("DROP TYPE IF EXISTS pet_species")
    op.execute("DROP TYPE IF EXISTS auth_provider")
    # ### end Alembic commands ###
