"""add guide documents and transport pet rules

Revision ID: 972f1e5041f8
Revises: c942fe532f72
Create Date: 2026-08-27 19:03:06.382398
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "972f1e5041f8"
down_revision: str | Sequence[str] | None = "c942fe532f72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guide_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum("airline", "ferry", "preparation", name="guide_category"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guide_documents")),
        sa.UniqueConstraint("slug", name=op.f("uq_guide_documents_slug")),
    )
    op.create_index("ix_guide_documents_category", "guide_documents", ["category"], unique=False)
    op.create_index("ix_guide_documents_is_active", "guide_documents", ["is_active"], unique=False)
    op.create_table(
        "guide_document_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guide_document_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_note", sa.String(length=200), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("display_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["guide_document_id"],
            ["guide_documents.id"],
            name=op.f("fk_guide_document_sources_guide_document_id_guide_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guide_document_sources")),
    )
    op.create_index(
        "ix_guide_document_sources_guide_document_id",
        "guide_document_sources",
        ["guide_document_id"],
        unique=False,
    )
    op.create_table(
        "transport_pet_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guide_document_id", sa.UUID(), nullable=False),
        sa.Column("carrier_name", sa.String(length=50), nullable=False),
        sa.Column("carrier_type", sa.Enum("airline", "ferry", name="carrier_type"), nullable=False),
        sa.Column("route", sa.String(length=50), nullable=True),
        sa.Column("cabin_allowed", sa.Boolean(), nullable=True),
        sa.Column("cabin_max_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cabin_fee_krw", sa.Integer(), nullable=True),
        sa.Column("min_age_weeks_cabin", sa.SmallInteger(), nullable=True),
        sa.Column("max_pets_per_person_cabin", sa.SmallInteger(), nullable=True),
        sa.Column("max_pets_per_trip", sa.SmallInteger(), nullable=True),
        sa.Column("cargo_allowed", sa.Boolean(), nullable=True),
        sa.Column("cargo_max_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cargo_fee_threshold_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cargo_fee_light_krw", sa.Integer(), nullable=True),
        sa.Column("cargo_fee_heavy_krw", sa.Integer(), nullable=True),
        sa.Column("min_age_weeks_cargo", sa.SmallInteger(), nullable=True),
        sa.Column("pledge_required", sa.Boolean(), nullable=True),
        sa.Column("online_checkin_allowed", sa.Boolean(), nullable=True),
        sa.Column("same_day_request_allowed", sa.Boolean(), nullable=True),
        sa.Column("request_deadline_hours", sa.SmallInteger(), nullable=True),
        sa.Column("airport_cage_price_krw", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cabin_fee_krw IS NULL OR cabin_fee_krw >= 0",
            name=op.f("ck_transport_pet_rules_cabin_fee_nonnegative"),
        ),
        sa.CheckConstraint(
            "cabin_max_weight_kg IS NULL OR cabin_max_weight_kg >= 0",
            name=op.f("ck_transport_pet_rules_cabin_max_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "cargo_max_weight_kg IS NULL OR cargo_max_weight_kg >= 0",
            name=op.f("ck_transport_pet_rules_cargo_max_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes > 0",
            name=op.f("ck_transport_pet_rules_duration_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["guide_document_id"],
            ["guide_documents.id"],
            name=op.f("fk_transport_pet_rules_guide_document_id_guide_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transport_pet_rules")),
    )
    op.create_index(
        "ix_transport_pet_rules_carrier_type", "transport_pet_rules", ["carrier_type"], unique=False
    )
    op.create_index(
        "ix_transport_pet_rules_guide_document_id",
        "transport_pet_rules",
        ["guide_document_id"],
        unique=False,
    )
    op.create_table(
        "transport_restricted_breeds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transport_pet_rule_id", sa.UUID(), nullable=False),
        sa.Column("breed_name_ko", sa.String(length=100), nullable=False),
        sa.Column("breed_name_en", sa.String(length=100), nullable=True),
        sa.Column("breed_aliases", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "restriction_type",
            sa.Enum("dangerous", "brachycephalic", name="breed_restriction_type"),
            nullable=False,
        ),
        sa.Column(
            "applies_to",
            sa.Enum("cabin", "cargo", "both", name="breed_restriction_scope"),
            nullable=False,
        ),
        sa.Column("is_example_only", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["transport_pet_rule_id"],
            ["transport_pet_rules.id"],
            name=op.f("fk_transport_restricted_breeds_transport_pet_rule_id_transport_pet_rules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transport_restricted_breeds")),
    )
    op.create_index(
        "ix_transport_restricted_breeds_breed_name_ko",
        "transport_restricted_breeds",
        ["breed_name_ko"],
        unique=False,
    )
    op.create_index(
        "ix_transport_restricted_breeds_rule_id",
        "transport_restricted_breeds",
        ["transport_pet_rule_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transport_restricted_breeds_rule_id", table_name="transport_restricted_breeds"
    )
    op.drop_index(
        "ix_transport_restricted_breeds_breed_name_ko", table_name="transport_restricted_breeds"
    )
    op.drop_table("transport_restricted_breeds")
    op.drop_index("ix_transport_pet_rules_guide_document_id", table_name="transport_pet_rules")
    op.drop_index("ix_transport_pet_rules_carrier_type", table_name="transport_pet_rules")
    op.drop_table("transport_pet_rules")
    op.drop_index(
        "ix_guide_document_sources_guide_document_id", table_name="guide_document_sources"
    )
    op.drop_table("guide_document_sources")
    op.drop_index("ix_guide_documents_is_active", table_name="guide_documents")
    op.drop_index("ix_guide_documents_category", table_name="guide_documents")
    op.drop_table("guide_documents")
    # ### end Alembic commands ###
