export const colors = {
  primary: '#FF8A3D',
  secondary: '#4CAF88',
  background: '#FFFFFF',
  surface: '#FFFFFF',
  mintBg: '#EEF8F5',
  mintIcon: '#52B9A5',
  orangeBg: '#FFF3EA',
  orangeIcon: '#FF8A4C',
  iconGray: '#7E8582',
  neutralGray: '#F5F6F4',
  textPrimary: '#333333',
  textSecondary: '#7A7A7A',
  border: '#EEEEEA',
  divider: '#E5E5E5',
  success: '#2EAF6D',
  warning: '#F5A623',
  error: '#E5484D',
  /** 경고 아이콘·배지 배경으로 쓰는 연한 코랄 */
  errorBg: '#FDECEC',
} as const;
